ALTER TABLE users
  MODIFY COLUMN quota BIGINT NULL DEFAULT 0,
  MODIFY COLUMN used_quota BIGINT NULL DEFAULT 0,
  MODIFY COLUMN aff_quota BIGINT NULL DEFAULT 0,
  MODIFY COLUMN aff_history BIGINT NULL DEFAULT 0;
